config/routes.rb
Coketas::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'site#index'
  get 'catalogo(/:id)' => 'site#catalogo', :as => :catalogo
  get 'stock', :to => 'site#stock'
  get 'contacto', :to => 'site#contacto'
  post 'contacto', :to => 'site#send_mail'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_many :fotos
  has_and_belongs_to_many :productos, :join_table => :colors_productos
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  attr_accessible :consulta, :direccion, :email, :nombre, :telefono
  validates :email, :nombre, :consulta, :presence => true
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  attr_accessible :imagen, :producto_id

  belongs_to :producto
  belongs_to :color
  validates :producto_id, :imagen, :presence => true

  has_attached_file :imagen,
  	:styles => { :medium => "624", :thumb => "202", :min => "100" },
    :storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :dropbox_options => {
      :path => proc { |style| "producto/#{style}/#{id}_#{imagen.original_filename}" }
    }
end

app/models/marca.rb
class Marca < ActiveRecord::Base
  attr_accessible :nombre, :descripcion, :foto

  validates :nombre, :foto, :presence => true
  validates :nombre, :uniqueness => true
  
  has_many :producto

  has_attached_file :foto,
  	:styles => { :standar => "224x168>"},
    :storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :dropbox_options => {
      :path => proc { |style| "marca/#{style}/#{id}_#{foto.original_filename}" }
    }
end

app/models/new.rb
class New < ActiveRecord::Base
  attr_accessible :titulo, :info, :foto
  validates :titulo, :info, :foto, :presence => true
  has_attached_file :foto,
  	:styles => { :medium => "624x458>"},
    :storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :dropbox_options => {
      :path => proc { |style| "new/#{style}/#{id}_#{foto.original_filename}" }
    }
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  attr_accessible :codigo, :color_ids, :descripcion, :marca_id, :nombre, :precio, :stock, :talle_ids, :foto
  
  validates :codigo, :marca_id, :nombre, :stock, :presence => true
  validates :codigo, :uniqueness => true

  belongs_to :marca
  has_many :fotos
  has_and_belongs_to_many :talles, :join_table => :productos_talles
  has_and_belongs_to_many :colors, :join_table => :colors_productos
  
  accepts_nested_attributes_for :talles
  accepts_nested_attributes_for :colors

end

app/models/talle.rb
class Talle < ActiveRecord::Base
  attr_accessible :nombre
  validates :nombre, :presence => true
  validates :nombre, :uniqueness => true
  has_and_belongs_to_many :productos, :join_table => :productos_talles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/color_controller.rb
class ColorController < InheritedResources::Base
end

app/controllers/marca_controller.rb
class MarcaController < InheritedResources::Base
end

app/controllers/producto_controller.rb
class ProductosController < InheritedResources::Base
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def index
		@News = New.limit(5)
	end

	def catalogo
		if params[:id] 
			@Productos = Producto.where(:marca_id => params[:id])
			@Marca_actual = Marca.find_by_id(params[:id])
		else
			@Productos = Producto.where(:marca_id => Marca.first.id) if Marca.first
			@Marca_actual = Marca.first
		end
		@Marcas = Marca.all
	end

	def stock
		@Productos = Producto.where("stock > 0")
	end

	def send_mail
		UserMailer.default_url_options[:host] = request.host_with_port
		@contacto = Contacto.new(params[:contacto])
		UserMailer.contact_confirmation(@contacto).deliver
		if @contacto.save
			flash[:notice] = "El e-mail se envio correctamente"
			redirect_to root_path
		else
			flash[:notice] = "Debes completar los campos"
			redirect_to contacto_path
		end
	end
end

app/controllers/talle_controller.rb
class TalleController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8" />

	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title><%= content_for?(:title) ? yield(:title) : "Coketas" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
   <%= render "shared/header" %>
   <p id="notice"><%= notice %></p>
    <%= yield %>
    <%= render "shared/footer" %>
  </div>
</body>

<script type="text/javascript" data-turbolinks-eval=false>
  $(window).load(function() {
    $('#slider').orbit({
      animation: 'horizontal-push',
      captions: false,
      bullets: false
      });
  });
</script>
</html>

app/views/shared/_footer.html.slim
footer
  h1 by
  a href="http://www.nibyru.com" target="_blank"
    = image_tag("Nibyru.png")

app/views/shared/_header.html.slim
header
  = link_to root_path , :class => "logo" do
    h1 coketas
  form.login
    label Usuario:
    input type="text"
    label Contraseña:
    input type="password"
    input type="submit" value=""

app/views/shared/_menu.html.slim
.menu
  #menu-btn
    span
  ul
    li = link_to_unless_current "inicio", root_path, "data-no-turbolink" => "" do
      p inicio
    li = link_to_unless_current "catalogo", catalogo_path do
      p catalogo
    li.stock = link_to_unless_current "stock", stock_path do
      p stock
    li = link_to_unless_current "contacto", contacto_path do
      p contacto

    .social
      a.facebook href="http://www.facebook.es" target="_blank"
      a.google-plus href="http://www.gmail.com" target="_blank"
      a.twitter href="http://www.twitter.com" target="_blank"
  
  #menu-btn-close
    span

app/views/site/catalogo.html.slim
nav
  = render "shared/menu"

section
  - if @Marcas && @Marca_actual
      .catalogo

        .lista_marcas
          ul
            - @Marcas.each do |m|
              li
                = link_to m.nombre, catalogo_path(:id => m.id)
          = image_tag(@Marca_actual.foto.url(:standar))

        .lista_fotos
          - @Productos.each do |p|
            - p.fotos.each do |f|
                    = link_to f.imagen.url, :rel=>"lightbox-catalogo", :title => "cod. #{p.codigo} - #{p.nombre} - #{p.descripcion} - $#{p.precio}" do
                        = image_tag(f.imagen.url(:thumb))
  -  else
      .mensaje
        h2 Todavía no cargaste ninguna marca
        p
        |Puedes cargarlas desde 
        = link_to "aquí", admin_root_path

app/views/site/contacto.html.slim
nav
  = render "shared/menu"

section
  = form_for :contacto, url: { action: "contacto" }, html: {class: "contacto"} do |f|
    h1 Comentanos las dudas y sugerencias que tengas...
    h2 Gracias por ayudarnos a brindar un mejor servicio cada día.
    = f.label :nombre
    = f.text_field :nombre, :required => true
    = f.label :email
    = f.email_field :email, :required => true
    = f.label :telefono
    = f.telephone_field :telefono
    = f.label :direccion
    = f.text_field :direccion
    = f.label :consulta, :size => "60x12", :required => true
    = f.text_area :consulta, :size => "60x12", :required => true
    = f.submit "Enviar"
  .deco
    =image_tag("deco.gif")

app/views/site/index.html.slim
nav
  = render "shared/menu"

section
	- if @News.count != 0
	  #slider
	    - @News.each do |n|
	      .item
	        = image_tag(n.foto.url(:medium))
	        .caption
	          h1 = n.titulo
	          p = n.info
	- else
      .mensaje
        h2 Todavía no cargaste ninguna noticia
        p
        |Puedes cargarlas desde 
        = link_to "aquí", admin_root_path

app/views/site/stock.html.slim
nav
  = render "shared/menu"

section
  .tabla-stock
    p Productos disponibles
    table#stock
      thead
        tr
          th código
          th producto
          th marca
          th color
          th talle
          th stock
          th ver
      tbody
        - @Productos.each do |p|
          tr
            td = p.codigo
            td = p.nombre
            td = Marca.find(p.marca_id).nombre if Marca.find_by_id(p.marca_id)
            td = (p.colors.order('nombre').map{ |c| c.nombre}).join(' , ')
            td = (p.talles.order('nombre').map{ |t| t.nombre }).join(' , ')
            td = p.stock
            td style="max-width: 100px"
              - p.fotos.each do |f|
                  = link_to f.imagen.url, :rel=>"lightbox-#{p.codigo}", :title => "cod. #{p.codigo} - #{p.nombre} - #{p.descripcion} - $#{p.precio}" do
                      span.ver
          